name: Keep Clipnote Alive

on:
  schedule:
    - cron: "*/10 * * * *"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/keepalive.yml"

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Curl ping clipnote site
        run: |
          echo "Pinging Clipnote to keep it awake..."
          curl -s -o /dev/null -w "%{http_code}" https://clipnote.muskansindhu.tech
